version: 0.2
phases:
  build:
    commands:
      # make build dir
      - mkdir build
      - cd build
      - cmake ..
      # build the application
      - cmake --build .
artifacts:
  files:
    - build/*